### ISSUE TITLE
No plugin file or installation instructions

### ISSUE THREAD

**Issue by ghost** [KillerBOSS2019/TP-YTDM-Plugin#11]
The installation instructions don't actually explain how to install the plugin at all. There is no tpp file. What am I supposed to do with this to make it work?

**Comment by gitagogaming** [comment]
You can download the most recent version of the plugin here - https://github.com/KillerBOSS2019/TP-YTDM-Plugin/releases

**Comment by ghost** [comment]
My bad. Thank you.
