### ISSUE TITLE
Dislike Function working different than dislike in ytmd

### ISSUE THREAD

**Issue by T3dw4rd** [KillerBOSS2019/TP-YTDM-Plugin#3]
The dislike feature seems to just skip to the next track and not interact with the dislike flag in YouTube Music.

When I dislike a track through the plug-in it goes to the next track, but it does not actually dislike the track on YTmD. However, if I dislike a track in YTmD it goes to the next song and when I go back to the track it shows as DISLIKED both in the app and through the plug-in. Similarly, if the track is disliked I can clear the dislike in the YTmD app and the song continues to play, but if I try to hit the dislike through the plug-in it skips to the next track ad the dislike flag is still set on the song.

 I made a quick video to show the issue. hope it helps
https://drive.google.com/file/d/1kHP3E_JxP_L5RS4lM4ehcDWiUZWzCAaI/view?usp=sharing

**Comment by DamienStaebler** [comment]
Thank you for the report but I don't think I can do anything with my plugin since it's the actual program(The YTMD app) is making the glitch so uhh I'll report this to the dev of YTMD app Thank you for the report! (Sorry I am bad at english)
