### ISSUE TITLE
Feature: Play/Pause Event

### ISSUE THREAD

**Issue by LorenAtInnovise** [KillerBOSS2019/TP-YTDM-Plugin#5]
This is a great plugin. Is there a possibility of adding a play/pause event? This could be used for declaratively changing the button icon from a play to pause.

**Comment by DamienStaebler** [comment]
It should be already possible using "When plugin state changes to {value}" then do something

**Comment by DamienStaebler** [comment]
But yes I could add it as on its own

**Comment by LorenAtInnovise** [comment]
Oh this is helpful. What are the value for the states? I tried "Play" and "play" with no luck.

**Comment by DamienStaebler** [comment]
> Oh this is helpful. What are the value for the states? I tried "Play" and "play" with no luck.

Uh I don't remember but you could use check it by using "Update somestates at 500ms" something like that

**Comment by DamienStaebler** [comment]
Events is added in next version It's right now under testing and there is alot more is in this new version!
